

log_directory: "logs"
RateLimiterService:
  local_host : "localhost"
  docker_host : "host.docker.internal"

  Mongo_config_data:
    - service: "MongoDB Instance 1"
      category: "MongoDB"
      port: 27031
    - service: "MongoDB Instance 2"
      category: "MongoDB"
      port: 27032
    - service: "MongoDB Instance 3"
      category: "MongoDB"
      port: 27033
    - service: "MongoDB Instance 4"
      category: "MongoDB"
      port: 27034
    - service: "MongoDB Instance 5"
      category: "MongoDB"
      port: 27035
    - service: "MongoDB Instance 6"
      category: "MongoDB"
      port: 27037

  Redis_request_data:
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7000
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7001
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7002
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7003
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7004
    - service: "RateLimiterService RequestRedis Cluster"
      category: "RequestRedis Cluster"
      port: 7005

  Redis_config_data:
    - service: "RateLimiterService ConfigRedis"
      category: "ConfigRedis"
      port: 8000

  service_port: 
    - service: "RateLimiterService"
      category: "Main Port"
      port : 6002

GateWayService:
    local_host : "localhost"
    docker_host : "host.docker.internal"
    service_port:
      - service: "GateWayService"
        category: "Main Port"    
        port : 6001

AuthenticationService:
    local_host : "localhost"
    docker_host : "host.docker.internal"
    service_port:
      - service: "AuthenticationService"
        category: "Main Port"      
        port : 6003

    Redis_auth_service:
      - service: "AuthenticationService Redis"
        category: "Redis"
        port: 8001

ClientService:
    local_host : "localhost"
    docker_host : "host.docker.internal"
    service_port:
      - service: "ClientService"
        category: "Main Port"
        port : 6004

    Redis_client_service:
      - service: "ClientService Redis"
        category: "Redis"
        port: 8002

CollaborationService:
    local_host : "localhost"
    docker_host : "host.docker.internal"
    service_port:
    - service: "CollaborationService"
      category: "Main Port"    
      port : 6005

    Redis_collab_service:
      - service: "CollaborationService Redis"
        category: "Redis"
        port: 8002

LoadService:
    local_host : "localhost"
    docker_host : "host.docker.internal"
    service_port:
    - service: "LoadService"
      category: "Main Port" 
      port : 6006




